<?php

	namespace App\Tests\Controller\Fonctionnel;

	use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

	class TaskControllerTest extends WebTestCase
	{
		protected function setUp(): void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
		}

		public function testListTasks(): void
		{

		}
	}