<?php

	namespace App\Tests\Controller\Fonctionnel;

	use Symfony\Bundle\FrameworkBundle\KernelBrowser;
	use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
	use Symfony\Component\DomCrawler\Crawler;

	class UserControllerTest extends WebTestCase
	{
		private Crawler $crawler;
		private KernelBrowser $client;

		protected function setUp(): void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
			$this->client = static::createClient();
			$this->crawler = $this->client->request('GET', '/users');
			$this->assertResponseIsSuccessful();
		}

		public function testListUsersIsNotEmpty(): void
		{
			$this->assertSelectorNotExists('alert alert-warning', 'La liste apparait.');
			// $this->assertSelectorNotExists();Exists('row', 'Pas d\'utilisateur enregistrer.');
		}


	}